### ISSUE TITLE
Need to reinstall different version of bazel for Clion

### ISSUE THREAD

**Issue by ZackKnopp** [ZackKnopp/drake#1]
It automatically installed bazel 0.18.1 when to use drake with Clion you need bazel 0.16.1

To get around this I uninstalled bazel following: https://github.com/bazelbuild/bazel/issues/838

And reinstalled it using their installer: https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu

**Comment by ZackKnopp** [comment]
To install the specific Clion plugin you need to go to here: https://plugins.jetbrains.com/plugin/9554-bazel

And download the version required (for me it was 2018.08.06.0.1)

Then in Clion go File > Settings > Plugins > Install plugin from disk... 

And select the zip folder you just downloaded

**Comment by ZackKnopp** [comment]
Suggestions for docs:

Put MacOS workaround up top so people don't get into it and then realize they need work arounds.

Say you might need to check bazel version and reinstall correct version.

Show how to install specific plugin version from disk instead of from repo browsing.

**Comment by ZackKnopp** [comment]
Tried to build with bazel tool and got this error: 
```
ERROR: /home/zakaria/drake/WORKSPACE:28:1: Traceback (most recent call last):
	File "/home/zakaria/drake/WORKSPACE", line 28
		versions.check(minimum_bazel_version = "0.18.0")
	File "/home/zakaria/.cache/bazel/_bazel_zakaria/cc125f4491eb2285a37e006090b2e15a/external/bazel_skylib/lib/versions.bzl", line 104, in versions.check
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.16.1, expected at least 0.18.0
```

**Comment by ZackKnopp** [comment]
I installed the latest version of Clion: 2018.2.6
I installed bazel 0.18.0
I installed bazel plugin 2018.10.22.0.2

Import bazel project button in file is now operational and not greyed out

**Comment by ZackKnopp** [comment]
Opened an issue to update the docs: https://github.com/RobotLocomotion/drake/issues/10081
